---
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST}:${POSTGRESQL_SERVICE_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USER_DISTRIBUTION}
    password: ${POSTGRESQL_PASSWORD_DISTRIBUTION}
